WebNoiThat/WebNoiThat/Areas/Admin/Controllers/AdminPagesController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebNoiThat.Models;
using WebShop.Helpper;

namespace WebNoiThat.Areas.Admin.Controllers
{
    public class AdminPagesController : Controller
    {
        private readonly QLNoiThat _context;

        public AdminPagesController(QLNoiThat context)
        {
            _context = context;
        }
        public AdminPagesController()
        {
            _context = new QLNoiThat();
        }
        // GET: Admin/AdminPages
        public ActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsPages = _context.Pages
                .AsQueryable()
                .OrderByDescending(x => x.PageID);
            PagedList.IPagedList<Page> models = new PagedList<Page>(lsPages, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminPages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Page page = _context.Pages.Find(id);
            if (page == null)
            {
                return HttpNotFound();
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PageID,PageName,Contents,Thumb,Published,Title,MetaDesc,MetaKey,Alias,CreatedDate,Ordering")] Page page, HttpPostedFileBase fThumb)
        {
            if (ModelState.IsValid)
            {

                page.PageName = Utilities.ToTitleCase(page.PageName);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string imageName = Utilities.SEOUrl(page.PageName) + extension;
                    page.Thumb = await Utilities.UploadFile(fThumb, @"pages", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                page.Alias = Utilities.SEOUrl(page.PageName);
                _context.Entry(page).State = EntityState.Added;
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Thêm mới thành công";
                return RedirectToAction("Index");
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            
            var page = await _context.Pages.FindAsync(id);
            if (page == null)
            {
                return HttpNotFound();
            }
            return View(page);
        }

        // POST: Admin/AdminPages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Page page, HttpPostedFileBase fThumb, string imageName)
        {
            if (id != page.PageID)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    page.PageName = Utilities.ToTitleCase(page.PageName);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(page.PageName) + extension;
                        page.Thumb = await Utilities.UploadFile(fThumb, @"pages", image.ToLower());
                    }
                    else if (!string.IsNullOrEmpty(imageName))
                    {
                        page.Thumb = imageName;
                    }
                    if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                    page.Alias = Utilities.SEOUrl(page.PageName);
                    _context.Entry(page).State = EntityState.Modified;
                    TempData["Success"] = "Cập nhật thành công";
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PageExists(page.PageID))
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Page page = _context.Pages.Find(id);
            if (page == null)
            {
                return HttpNotFound();
            }
            return View(page);
        }

        // POST: Admin/AdminPages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Page page = _context.Pages.Find(id);
            _context.Pages.Remove(page);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        private bool PageExists(int id)
        {
            return _context.Pages.Any(e => e.PageID == id);
        }
    }
}

WebNoiThat/WebNoiThat/Areas/Admin/Views/AdminPages/Create.cshtml
@model WebNoiThat.Models.Page

@{
    ViewBag.Title = "Tạo mới pages";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Styles{
    <link href="~/DataHA/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/DataHA/Adminassets/summernote/summernote.css" rel="stylesheet" />
}
@using (Html.BeginForm("Create", "AdminPages", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="text-danger">@Html.ValidationSummary(false, "", new { @class = "text-danger" })</div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN PAGE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ </a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ProductName">Tên danh mục</label>
                        @Html.TextBoxFor(m => m.PageName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ShortDesc">Ordering</label>
                        @Html.TextBoxFor(m => m.Ordering, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Thumb, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="fThumb" />
                            @Html.ValidationMessageFor(model => model.Thumb, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <div class="checkbox">
                                        <input type="checkbox" id="Published" name="Published" checked value="true">
                                        <label for="Published"></label>
                                    </div>
                                </div>
                                <label>Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        @Html.TextBoxFor(model => model.MetaDesc, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        @Html.TextBoxFor(model => model.MetaKey, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    @Html.TextBoxFor(model => model.Contents, new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>
}
@section Scripts{
    <script src="~/DataHA/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/DataHA/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/DataHA/Adminassets/summernote/summernote-bs4.js"></script>
    <script>
        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebNoiThat/WebNoiThat/Areas/Admin/Views/AdminPages/Delete.cshtml
@model WebNoiThat.Models.Page

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Page</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contents)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contents)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thumb)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Published)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Published)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaKey)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ordering)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ordering)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebNoiThat/WebNoiThat/Areas/Admin/Views/AdminPages/Details.cshtml
@model WebNoiThat.Models.Page

@{
    ViewBag.Title = "Chi tiết Page";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="~/Admin/Home" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <span class="breadcrumb-item active">Thông tin Page: trang @Model.PageName</span>
        </nav>
    </div>
</div>
<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <a>
                <img width="200" height="200" src="~/DataHA/images/pages/@Model.Thumb" alt="@Model.Title" />
            </a>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.PageName</h4>
                <p class="text-muted m-b-0">ID: #@Model.PageID</p>
            </div>
        </div>
        <div class="m-b-15">
            <a href="@Url.Action("Edit", "AdminPages", new { id = Model.PageID })" class="btn btn-primary">Sửa đổi</a>
        </div>
    </div>
</div>
<h1>Chi tiết</h1>
<div>
    <h4>Page</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contents)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contents)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Published)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Published)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaKey)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ordering)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ordering)
        </dd>

    </dl>
</div>

WebNoiThat/WebNoiThat/Areas/Admin/Views/AdminPages/Edit.cshtml
@model WebNoiThat.Models.Page

@{
    ViewBag.Title = "Chỉnh sửa pages :" + Model.PageName;
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Styles{
    <link href="~/DataHA/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/DataHA/Adminassets/summernote/summernote.css" rel="stylesheet" />
}
@using (Html.BeginForm("Edit", "AdminPages", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="text-danger">@Html.ValidationSummary(true)</div>
    @Html.HiddenFor(m => m.PageID)
    @Html.HiddenFor(m => m.Thumb)
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN PAGES</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ CHI TIẾT</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ProductName">Tên Page</label>
                        @Html.TextBoxFor(m => m.PageName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ShortDesc">Ordering</label>
                        @Html.TextBoxFor(m => m.Ordering, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="fThumb">Ảnh đại diện</label>
                        <input type="file" name="fThumb" id="fThumb" />
                        @if (!string.IsNullOrEmpty(Model.Thumb))
                        {
                            <br />
                            <img src="@Url.Content("~/DataHA/images/pages/" + Model.Thumb)" alt="@Model.PageName" class="img-thumbnail" />
                            <br />
                            <label for="imageName">Image Name</label>
                            <input type="text" name="imageName" id="imageName" value="@Model.Thumb" class="form-control" />
                        }
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <div class="checkbox">
                                        <input type="checkbox" id="Published" name="Published" checked value="true">
                                        <label for="Published"></label>
                                    </div>
                                </div>
                                <label>Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        @Html.TextBoxFor(model => model.MetaDesc, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        @Html.TextBoxFor(model => model.MetaKey, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    @Html.TextBoxFor(model => model.Contents, new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>
}
@section Scripts{
    <script src="~/DataHA/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/DataHA/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/DataHA/Adminassets/summernote/summernote-bs4.js"></script>
    <script>
 jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

WebNoiThat/WebNoiThat/Areas/Admin/Views/AdminPages/Index.cshtml
@model PagedList.IPagedList<WebNoiThat.Models.Page>
@using PagedList.Mvc
@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách Page" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="~/Admin/Home" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <span class="breadcrumb-item active">Danh sách Pages :</span>
        </nav>
    </div>
</div>
<div class="col-lg-4 text-left">
    <a class="btn btn-primary" href="/Admin/AdminPages/Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm Page</span></a>
</div>
<div class="table-responsive">
    <table class="table table-hover e-commerce-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tên Page</th>
                <th>Trạng thái</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    string url = $"/page/{item.Alias}";
                    <tr>
                        <td>@item.PageID</td>
                        <td><a target="_blank" href="@url">@item.PageName</a></td>
                        <td>
                            @if (item.Published == true)
                            {


                                <div class="d-flex align-items-center">
                                    <div class="badge badge-success badge-dot m-r-10"></div>
                                    <div>Public</div>
                                </div> }
                            else
                            {
                                <div class="d-flex align-items-center">
                                    <div class="badge badge-success badge-dot m-r-10"></div>
                                    <div>Non-Public</div>
                                </div>}


                        </td>

                        <td>
                            <a class="btn btn-primary btn-tone m-r-5" href="@Url.Action("Details", "AdminPages", new { area = "Admin", id = item.PageID })">Chi tiết</a>
                            <a class="btn btn-secondary btn-tone m-r-5" href="@Url.Action("Edit", "AdminPages", new { area = "Admin", id = item.PageID })">Sửa</a>
                            <a class="btn btn-success btn-tone m-r-5" href="@Url.Action("Delete", "AdminPages", new { area = "Admin", id = item.PageID })">Xóa</a>
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
    <div aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item @(!Model.HasPreviousPage ? "disabled" : "")">
                <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber - 1 })" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for (int i = 1; i <= Model.PageCount; i++)
            {
                <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                    <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
                </li>
            }
            <li class="page-item @(!Model.HasNextPage ? "disabled" : "")">
                <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber + 1 })" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </div>
</div>
  